#pragma once

typedef struct _SET_BLACK_WORKITEM_CONTEXT {
    UNICODE_STRING symLink;
} SET_BLACK_WORKITEM_CONTEXT, * PSET_BLACK_WORKITEM_CONTEXT;

WDF_DECLARE_CONTEXT_TYPE(SET_BLACK_WORKITEM_CONTEXT);

NTSTATUS CreateWorkItemForIoTargetOpenDevice(WDFDEVICE device, CONST UNICODE_STRING& symLink);
NTSTATUS SetBlackAsync(WDFDEVICE device, 
    CONST UNICODE_STRING& symLink);